name: a_group
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.8
  equatable: ^2.0.5
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  google_fonts: 6.1.0
  flutter_svg: ^2.0.10+1
  yandex_geocoder: ^2.3.1
  yandex_mapkit: ^4.0.2
  mask_text_input_formatter: ^2.9.0
  image_picker: ^1.0.8
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/gca-1.png"
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
